dbt_project:
fictional_lab_dbt:
  outputs:
    dev:
      dataset: fictional_lab_dataset
      job_execution_timeout_seconds: 600
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: fictional-lab-dev
      threads: 3
      type: bigquery
  target: dev