WITH CTE_RAW_CUSTOMERS AS (
SELECT CUSTOMER_ID,
  FIRST_NAME,
  LAST_NAME,
  EMAIL,
  PHONE,
  ADDRESS,
  CREATED_AT,
  ROW_NUMBER() OVER(PARTITION BY CUSTOMER_ID ORDER BY CREATED_AT DESC) AS ROW_RANK
FROM {{ source('fictional_lab_dataset', 'raw_customers') }}
)
SELECT CUSTOMER_ID,
  FIRST_NAME,
  LAST_NAME,
  EMAIL,
  PHONE,
  ADDRESS,
  CREATED_AT
FROM CTE_RAW_CUSTOMERS
WHERE ROW_RANK = 1
