WITH CTE_RAW_PRODUCTS AS (
SELECT PRODUCT_ID,
  SKU,
  PRODUCT_NAME,
  CATEGORY,
  UNIT_PRICE,
  IS_ACTIVE,
  CREATED_AT,
  ROW_NUMBER() OVER(PARTITION BY PRODUCT_ID ORDER BY CREATED_AT DESC) AS ROW_RANK
FROM {{ source('fictional_lab_dataset', 'raw_products') }}
)
SELECT PRODUCT_ID,
  SKU,
  PRODUCT_NAME,
  CATEGORY,
  UNIT_PRICE,
  IS_ACTIVE,
  CREATED_AT
FROM CTE_RAW_PRODUCTS
WHERE ROW_RANK = 1