
version: 2

sources:
  - name: fictional_lab_dataset
    tables:
      - name: raw_customers
        description: "Customer data model"
        columns:
          - name: CUSTOMER_ID
            description: "The primary key for this table"
            data_tests:
              - not_null

      - name: raw_stores
        description: "Store data model"
        columns:
          - name: STORE_ID
            description: "The primary key for this table"
            data_tests:
              - not_null

      - name: raw_products
        description: "Product data model"
        columns:
          - name: PRODUCT_ID
            description: "The primary key for this table"
            data_tests:
              - not_null
      
      - name: raw_transactions
        description: "Transaction data model"
        columns:
          - name: TRANSACTION_ID
            description: "The primary key for this table"
            data_tests:
              - not_null
      
      - name: raw_transaction_items
        description: "Transaction item data model"
        columns:
          - name: TRANSACTION_ITEM_ID
            description: "The primary key for this table"
            data_tests:
              - not_null
