WITH CTE_RAW_STORES AS (
SELECT STORE_ID,
  STORE_NAME,
  REGION,
  COUNTRY,
  STATE,
  POSTCODE,
  MANAGER_NAME,
  ROW_NUMBER() OVER(PARTITION BY STORE_ID ORDER BY STORE_NAME DESC) AS ROW_RANK
FROM {{ source('fictional_lab_dataset', 'raw_stores') }}
)
SELECT STORE_ID,
  STORE_NAME,
  REGION,
  COUNTRY,
  STATE,
  POSTCODE,
  MANAGER_NAME
FROM CTE_RAW_STORES
WHERE ROW_RANK = 1