WITH CTE_RAW_TRANSACTION_ITEMS AS (
SELECT TRANSACTION_ITEM_ID,
  TRANSACTION_ID,
  PRODUCT_ID,
  QUANTITY,
  UNIT_PRICE,
  LINE_TOTAL,
  ROW_NUMBER() OVER(PARTITION BY TRANSACTION_ITEM_ID ORDER BY LINE_TOTAL DESC) AS ROW_RANK
FROM {{ source('fictional_lab_dataset', 'raw_transaction_items') }}
)
SELECT TRANSACTION_ITEM_ID,
  TRANSACTION_ID,
  PRODUCT_ID,
  QUANTITY,
  UNIT_PRICE,
  LINE_TOTAL
FROM CTE_RAW_TRANSACTION_ITEMS
WHERE ROW_RANK = 1
