WITH CTE_RAW_TRANSACTIONS AS (
SELECT TRANSACTION_ID,
  CUSTOMER_ID,
  STORE_ID,
  TRANSACTION_DATE,
  PAYMENT_METHOD,
  STATUS,
  TOTAL_AMOUNT,
  CREATED_AT,
  ROW_NUMBER() OVER(PARTITION BY TRANSACTION_ID ORDER BY CREATED_AT DESC) AS ROW_RANK
FROM {{ source('fictional_lab_dataset', 'raw_transactions') }}
)
SELECT TRANSACTION_ID,
  CUSTOMER_ID,
  STORE_ID,
  TRANSACTION_DATE,
  PAYMENT_METHOD,
  STATUS,
  TOTAL_AMOUNT,
  CREATED_AT
FROM CTE_RAW_TRANSACTIONS
WHERE ROW_RANK = 1
