name: Pipeline Fictional Lab Load Pipeline
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy Load Pipeline
    runs-on: ubuntu-latest
    environment: development
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      INSTANCE_CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Check Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GH_GCP_SA_KEY }}
      
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Deploy to Cloud Run Job
        run: |
          gcloud run jobs deploy fictional-lab-load-pipeline \
          --source Pipeline/FictionalLab/DataLoad \
          --region ${{ secrets.GCP_REGION }} \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --service-account "fictional-lab-service-account@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com" \
          --max-retries 0 \
          --set-env-vars INSTANCE_CONNECTION_NAME=${{ secrets.INSTANCE_CONNECTION_NAME }},DB_NAME=${{ secrets.DB_NAME }},DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_SCHEMA=${{ secrets.DB_SCHEMA }},DATASET_ID=${{ secrets.DATASET_ID }}